# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTo1CSwwAOF1-9Eu1STnw8x0f8kob5yu
"""

# Simple Encryption / Decryption

message = input("Enter message: ")
key = 3

# Encryption
encrypted = ""

for char in message:
    encrypted += chr(ord(char) + key)

print("Encrypted:", encrypted)

# Decryption
decrypted = ""

for char in encrypted:
    decrypted += chr(ord(char) - key)

print("Decrypted:", decrypted)